//! Versioned model, validation, compilation, and persistence for the new macro system.
pub mod asset_authoring;
pub mod authoring_analysis;
pub mod authoring_fields;
pub mod call_graph;
pub mod compiler;
pub mod coordinates;
pub mod editor_mutation;
pub mod executor;
pub mod hotkeys;
pub mod image_search;
pub mod input;
pub mod interpolation;
pub mod invocation;
pub mod invocation_prompt;
pub mod keyboard;
pub mod launcher_command;
pub mod launcher_query;
pub mod model;
pub mod notifications;
pub mod ocr;
pub mod package;
pub mod prompt;
pub mod recorder;
pub mod recorder_hooks;
pub mod recorder_hotkeys;
pub mod recorder_keyboard;
pub mod recorder_observer;
pub mod recorder_processor;
pub mod recorder_runtime;
pub mod recorder_semantics;
pub mod recorder_suggestions;
pub mod recorder_windows;
mod reusable_validation;
pub mod runtime;
pub mod screen;
pub mod store;
pub mod structure;
pub mod templates;
pub mod uia;
pub mod validation;
pub mod variables;
pub mod virtual_desktops;
pub mod windows;
pub use crate::image_crop::{ImageCropRect, crop_rgba, validate_crop_rect};

pub use asset_authoring::*;
pub use compiler::*;
pub use coordinates::*;
pub use executor::*;
pub use image_search::*;
pub use interpolation::*;
pub use invocation::*;
pub use keyboard::*;
pub use launcher_command::*;
pub use launcher_query::*;
pub use model::*;
pub use notifications::*;
pub use ocr::*;
pub use package::*;
pub use prompt::*;
pub use recorder::*;
pub use recorder_hooks::*;
pub use recorder_keyboard::*;
pub use recorder_observer::*;
pub use recorder_processor::*;
pub use recorder_runtime::*;
pub use recorder_semantics::*;
pub use recorder_suggestions::*;
pub use recorder_windows::*;
pub use runtime::{
    BreakpointOccurrence, CommandResult, CompletedStep, CompletedStepOutcome, DebugSnapshot,
    DiagnosticKey, MacroDiagnosticKey, MacroRuntime, MacroStepKey, RuntimeCommand, RuntimeOrigin,
    RuntimePauseReason, RuntimeRunMode, RuntimeSnapshot, RuntimeState, StepState,
};
pub use screen::*;
pub use store::*;
pub use structure::*;
pub use templates::*;
pub use uia::*;
pub use validation::*;
pub use variables::*;
pub use virtual_desktops::*;
pub use windows::*;
