name: Rust (Windows + nextest)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test-windows:
    name: Build & test on Windows (MSVC)
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        # On windows-latest the default host is already x86_64-pc-windows-msvc.

      - name: Cache cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            ~\.cargo\registry
            ~\.cargo\git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Build (debug, all targets)
        run: cargo build --locked --all-targets --verbose

      - name: Test (cargo-nextest)
        run: cargo nextest run --locked --workspace --all-features --no-fail-fast --failure-output=immediate-final
